#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!

sudo apt -y update
sudo apt install -y nginx

sudo mkdir /var/www/hello
sudo chown -R "$USER":"$USER" /var/www/hello
chmod 755 /var/www/hello
echo "Hello World!" > /var/www/hello/hello.html

sudo touch /etc/nginx/sites-available/hello
sudo chown "$USER":"$USER" /etc/nginx/sites-available/hello
cat > /etc/nginx/sites-available/hello << _EOL_
server {
listen 80 default_server;
listen [::]:80 default_server;
root /var/www/hello;
index hello.html;
}
_EOL_

sudo ln -s /etc/nginx/sites-available/hello /etc/nginx/sites-enabled/
sudo mv /etc/nginx/sites-enabled/default /home/ubuntu/

sudo service nginx restart
