#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!


if ! nginx -v; then
	sudo apt -y update
	sudo apt install -y nginx
fi

sudo touch /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
cat > /etc/nginx/sites-available/default << _EOL_
server {
listen 80 default_server;
listen [::]:80 default_server;
root /var/www/html;
index index.html;
location / {
	try_files \$uri \$uri/ =404;
}
}
_EOL_
if [ ! -e "/etc/nginx/sites-enabled/default" ]; then
	sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
fi

sudo service nginx restart
