#!/usr/bin/env bash
#Install nginx on your web-01 server

apt install -y nginx

cp /var/www/html/index.nginx-debian.html /var/www/html/new_index.nginx-debian.html

echo "Hello World!" > /var/www/html/index.nginx-debian.html

