#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!


if ! nginx -v; then
	sudo apt -y update
	sudo apt install -y nginx
fi

sudo touch /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

if  [ ! -e "default_backup" ]; then
	sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
fi
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "5i $new_string" /etc/nginx/sites-available/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
