#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!
# The redirection must be a “301 Moved Permanently”

if ! nginx -v; then
	sudo apt -y update
	sudo apt install -y nginx
fi

sudo touch /var/www/html/index.html /var/www/html/404.html
sudo chown -R "$USER":"$USER" /var/www/html/index.html /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

if  [ ! -e "default_backup" ]; then
	sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
fi
cat > /etc/nginx/sites-available/default << _EOL_
server {
listen 80 default_server;
listen [::]:80 default_server;
root /var/www/html;
index index.html;
location / {
        try_files \$uri \$uri/ =404;
}
}
_EOL_

new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "7i $new_string" /etc/nginx/sites-available/default

new_string="\\\terror_page 404 /404.html;"
sudo sed -i "9i $new_string" /etc/nginx/sites-available/default

if [ ! -e "/etc/nginx/sites-enabled/default" ]; then
        sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
fi

sudo service nginx restart
