#!/usr/bin/env bash
# Install nginx on your server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!
# The redirection must be a “301 Moved Permanently”
# Configure Nginx so that its HTTP response contains a custom header (X-Served-By HOSTNAME)

if ! nginx -v; then
        sudo apt -y update
        sudo apt install -y nginx
fi

sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

cat > /etc/nginx/sites-available/default << _EOL_
server {
listen 80 default_server;
listen [::]:80 default_server;
root /var/www/html;
index index.html;
server_name _;
add_header X-Served-By \$HOSTNAME;
location / {
	rewrite ^/redirect_me https://www.github.com/iAdamo permanent;
	error_page 404 /404.html;
        try_files \$uri \$uri/ =404;
}
}
_EOL_

sudo service nginx restart
