#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

if ! haproxy -v; then:
	sudo apt -y update
	sudo apt -y install --no-install-recommends software-properties-common
	sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
	sudo apt -y install haproxy=2.8.\*
fi
sudo chmod 666 /etc/haproxy/haproxy.cfg
cat >> /etc/haproxy/haproxy.cfg << _EOL_
frontend defines
	bind *:80
	mode http
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 248513-web-01 35.175.134.9:80
	server 248513-web-02 35.153.33.206:80
_EOL_
sudo chmod 644 /etc/haproxy/haproxy.cfg
sudo service haproxy restart
	
