#!/usr/bin/env bash
# Bash script that displays:
#
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
signal()
{
	echo "I am invincible!!!"
}
while ((1)); do
	trap signal SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
