#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS

while IFS=: read -r USER PASSWD U_ID G_ID USER_ID_IN HOME_DIR CMD_SH; do
        echo "The user $USER is part of the $G_ID gang, lives in $HOME_DIR and rides $CMD_SH. $U_ID's place is protected by the passcode $PASSWD, more info about the user here: $USER_ID_IN"
done </etc/passwd
