#!/usr/bin/env bash
# loops from 1 to 10 and
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
# You must use the while loop (for and until are forbidden)
# You must use the if, elif and else statements

i=0
while [[ "$i" -lt 10 ]]; do
	if [[ "$i" -eq 3 ]]; then
		echo "bad luck"
	elif [[ "$i" -eq 7 ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
