#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

#   Using the while loop (for and until are forbidden)
#   Using the case statement

i=1;
while [[ "$i" -lt 21 ]]; do
	case $i in 
	4 )  echo -e "$i\nbad luck from China"
		;;
        9 ) echo -e "$i\nbad luck from Japan"
		;;
        17 ) echo -e "$i\nbad luck from Italy"
		;;
        * ) echo "$i"
	esac
	(( i++ ))
done
