#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01.
#
# Requirements:
#
# The requirements below must be applied to web-01 (feel free to do it on lb-01 and web-02, but it won’t be checked)
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports:
#	22 (SSH)
#	443 (HTTPS SSL)
#	80 (HTTP)

if ! ufw version; then
    sudo apt -y update
    sudo apt install -y ufw
fi


sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

sudo ufw enable

sudo ufw status
sudo ufw reload
