#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
#
# Requirements:
#
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8        facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
